### ISSUE TITLE
User accounts for Beta 1 test

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#123]
We postpone the admin page and tiered account approval process, but need to create accounts specific to the roles and send our testers their logins.

There are three roles which will be tested: 
- Emergency Management, 
- Planer 
- First Responder

Those roles have access to different layers as specified here: https://docs.google.com/spreadsheets/d/1cSIux0LqNdfX63E37PuK44a3FjKaYc61WuKT1MbnbRo/edit#gid=8616709

Here is a list of all the people who will participate:
https://docs.google.com/spreadsheets/d/1QkrjpMLGP2KLf2WirywYUFG7idMydKhE0-vaQAPN0Vk/edit#gid=0

**Comment by ecaldwe1** [comment]
James thinks that it is better to just give them accounts. Allows us to control that they see what we want them to be able to see.

**Comment by mkrusche** [comment]
Please assign Victor and the two DCA testers to the Berkeley group.

**Comment by mkrusche** [comment]
New user was added by Tracy:

sean.thompson@dca.nj.gov	 	All Roles, Admin	Berkeley, Keansburg

**Comment by creinkin** [comment]
This is complete. All users specified in the google sheet have been given accounts on staging.njcoast.us. The mechanics are in place to limit their layer visibility but at the moment there are no municipality-specific or role-specific layers so the layer visibility was not assigned.

I have adjusted the map to put the users in a starting location based on their affiliation (determined by the 'keywords' field of the user model). All users affiliated solely with Berkeley will start there. Users with no affiliation, keansburg affiliation, or multiple affiliation (keansburg + other) will start in Keansburg.

I will share privately the user password list with the dev team.
