### ISSUE TITLE
Setup Account Sign In 

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#139]
As a tester 
I want to sign in with my username and password to gain access to the site.

AC:
- user can click on 'Sign In' button on the top right of the front page 
- access with a email address and Password popup before allowing the user to access the site
-- Change username to email address in sign in popup -> possible?
- username should be the testers email address

- omitted for Beta 1: user is able to change password, request forgot password, update email address

**Comment by creinkin** [comment]
Can we omit this for Beta 1? This would be custom functionality 
 - user is able to change password, request forgot password, update email address. 

Current status is that Geonode gives the change password and update email address options through the 'Profile' page but that page also has a *lot* of other links that we don't want to expose at the moment to the testers.

GeoNode doesn't look like it offers forgotten password help out of the box, so this might be custom functionality that needs to be written.

**Comment by mkrusche** [comment]
I edited the ticket to make clear that user profile features are omitted for Beta 1.
We will create users as detailed in https://app.zenhub.com/workspace/o/njcoast/cyberspatial/issues/123 and 
https://docs.google.com/spreadsheets/d/1QkrjpMLGP2KLf2WirywYUFG7idMydKhE0-vaQAPN0Vk/edit#gid=0

**Comment by creinkin** [comment]
This is now completed. The one hiccup is that there is a strange unicode error when using geonode's add members to group functionality if an email address is used as username. This seems to be a combination of using periods and '@' symbols. Talked to @mkrusche and decided to only use their email 'name' without the @ and domain portions for initial testing.
