### ISSUE TITLE
Deploy front and about page to njcoast.us

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#141]
As a user 
I am able to access the front and about page so that I get a general overview of the portal.

AC:
- User can access site without authentication
- Site is secured through SSL
- Template of the content for these two pages are the mockups from Kristina
   - Content for Frontpage http://www.crc.nd.edu/~kfurse/njcoast_berkeley/index.html 
   - Content for About Page http://www.crc.nd.edu/~kfurse/njcoast_berkeley/about.html
- Links to internal URL's (map view page, storm hazard projection tool page) should be removed

**Comment by creinkin** [comment]
I have modified the templates to remove all internal app links and have made it the basic project overview. @Omegaice fixed the two missing image links and redeployed it to the scratch container serving the njcoast.us site.

It is now on njcoast.us for testing and QA

**Comment by mkrusche** [comment]
Please change the URL for the University of Buffalo image in the bottom right on the About page from www.nd.edu to www.buffalo.edu.

**Comment by Omegaice** [comment]
I have changed the about page and pushed the new version.

**Comment by mkrusche** [comment]
Point www.njcoast.us to https://njcoast.us

**Comment by Omegaice** [comment]
I am not sure how to do this redirect with the kubernetes ingress controller (https://github.com/coreos/alb-ingress-controller) for AWS.
