### ISSUE TITLE
Export WMS into Geoserver

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#143]
Take the WMS links from the google doc from below to import layers. WMS need to go to Geoserver to add the layers. These layers are directly from the State NJ and are not coming from T&M. This serves as a workaround until T&M has made their data available again. 

https://docs.google.com/document/d/1iWXWoc4Qv3uoLQJbSET8O5v_hF1PYkOsOy0WPThzHVQ/edit

**Comment by mkrusche** [comment]
added link to Chuck's document which includes relevant WMS endpoints for layers

**Comment by creinkin** [comment]
I have all of the code in place to do this, tested today with @charlesvardeman. Reassigning to him to actually source and load in all the layers needed for Beta.
