### ISSUE TITLE
Frontend Cleanup

### ISSUE THREAD

**Issue by ecaldwe1** [NJCoast/cyberspatial#147]
- [x] Errors in console with static files
- [x] Template fits with site_base.html
- [x] remove unnecessary console log statements
- [x] update WMS endpoints for GIS map layers
- [x] remove  role/muni dropdown on the map view page top left
- [x] remove tool bar on map view page (top of the map)
- [x] remove all drop downs from menu bar on the top of the page, make only 'Map' and 'About' clickable  
- [x] remove 'map sharing' dropdown on top right on map view page 
- [x] disable buttons (annotation, run and explore simulation, Save, Copy buttons etc)  with tool tips
- [x] have storm visualization menu open by default when user comes to the map view page

**Comment by creinkin** [comment]
all of our custom views now use site_base.html instead of the main page using site_base and the map using base.html. base.html should be orphaned now and will delete it from the repo after Beta 1 is ready and stable

**Comment by creinkin** [comment]
These are all done. I decided to leave the logging in for now since it should help us with debugging any issues with the beta. I have tried to follow all links on the site and as a non-admin user I believe that every link goes somewhere legitimate and no unwanted links are still visible.
