### ISSUE TITLE
Fix squares in annotation shapes 

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#194]
Reduce the size of the squares all drawable shapes.

**Comment by Omegaice** [comment]
Problem is due to leaflet thinking that the computer has touch support enabled.

https://github.com/Leaflet/Leaflet.draw/blob/1dda7fa96c9a1dc71a5f46d7c832169962a5c0d0/src/draw/handler/Draw.Polyline.js#L50

**Comment by Omegaice** [comment]
For now assume that we are not using a touch screen.
