### ISSUE TITLE
On demand instances in Kubernetes for computational models

### ISSUE THREAD

**Issue by charlesvardeman** [NJCoast/cyberspatial#24]
It may be possible to use Kubernetes for primary job management of computational models. We don't want extra resources that are not needed, but to scale as necessary.

**Comment by Omegaice** [comment]
This is handled by the current implementation which spawns a job for each input file dropped into the S3 bucket. These jobs have a requirement on CPU time as well as Memory which should allow Kubernetes to schedule them appropriately.
