### ISSUE TITLE
Add muni switch

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#243]
As a user I want to change the muni so that I.

Prerequisite:
User belongs to more than one muni.

AC:
- [ ] User is able to select muni from a dropdown located
  - [ ] top left on the dashboard http://www.crc.nd.edu/~kfurse/njcoast_keansburg/dashboard-p.html 
        and
  - [ ] top left on the map view page http://www.crc.nd.edu/~kfurse/njcoast_keansburg/map-p.html
- [ ] Map focuses on the muni when switched 
- [ ] GIS layers are displayed according to the current role and muni

**Comment by chrissweet** [comment]
Done. Decided to switch out the users actual assigned muni from their muni list so state is preserved by model.
