### ISSUE TITLE
Dashboard - Additional muni requests

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#250]
As a user
I want to be able to select additional muni's beside the initial one
so I can have access to multiple muni's and their data.

Design approved by Tracy on June 11.

AC:
- [x] integrate button and corresponding UI according to Kristina's mockup: 
http://www.crc.nd.edu/~kfurse/njcoast_keansburg/dashboard-p_mr.html
- [ ] request need to go to DCA admin, not muni admin
- [ ] Change language in modal:![screenshot-www.crc.nd.edu-2018.06.11-14-26-36.png](https://images.zenhubusercontent.com/59f20d07a468affe6df84550/5e835187-98e1-42ae-aa72-9d4a83bf49d2)

NEW TEXT: “Users can request access only to municipalities for which they have legitimate business. To specify multiple municipalities simply type each municipality name and the form will autocomplete to match your request. Note that all access requests are subject to approval by NJcoast administrators. Once approved, any new municipalities will be listed in the Profile Section of your Dashboard. Switch between your approved municipalities using the dropdown at the top left of your Dashboard or Map view.”

**Comment by chrissweet** [comment]
Done
