### ISSUE TITLE
DCA Admin - Multiple Muni Approval

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#255]
As a DCA admin
I want to approve user with multiple muni requests
so that these users have access to more than one muni.

Kristina's mockup: http://www.crc.nd.edu/~kfurse/njcoast_admin/admin-dca-acct-req.html

AC: 
- [ ] user information in the gray box on the left (Name, Title, (primary) Municipality, Role and Justification should be re-printed from the original account request (to remind the DCA who the person is)
- [ ]  additional section added at the bottom listing the Additional Muni’s and the new Justification for multi-muni access
- [ ] all of the muni names (original primary muni, along with new add-ons) should be links to the profiles of the different muni approvers, so the DCA can easily query any of them, if needed
- [ ] note history (small gray italics above the Notes field on the right) showing original account request, muni-approval, DCA approval, any other notes, etc. ending in a date stamp for the new additional muni request
- [ ] in “All NJcoast Users” tab, user with multiple muni's, only original “primary” muni they originally applied within this column will be displayed, add asterisk or other symbol next to it indicating multi-muni access. (if clickin on "i" symbol, DCA can see full profil with list of muni's

**Comment by chrissweet** [comment]
Done
