### ISSUE TITLE
Documentation and Tutorials pages

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#257]
Create new subpages on Resources with the following structure

Resources
 - FAQ
 - SHP Tool
 - Documentation (VISIBLE TO LOGGED IN USER ONLY)
 - Tutorials  (VISIBLE TO LOGGED IN USER ONLY)

The Documentation page will contain the following table with text and hyperlinks to the pdf's, 
![screenshot-mail.google.com-2018.06.29-14-51-56.png](https://images.zenhubusercontent.com/59f20d07a468affe6df84550/8c70f613-bb20-4655-bf1e-65c1436e1bc1)
Files can be found here: https://drive.google.com/drive/u/0/folders/1HpVtapgo2HSKu_RuV-RwQGtSLylLdBbb?ths=true

Tutorials:
This page will include the following table with text, pdf's and YT videos (coming).
Following this structure:
![screenshot-mail.google.com-2018.06.29-14-46-52.png](https://images.zenhubusercontent.com/59f20d07a468affe6df84550/e0bd2f8f-8670-4656-995d-431e473c48f2) 
Files can be found here: https://drive.google.com/drive/u/0/folders/1De3S0yufmX1WKq8OhMzFDKJ53TGYFz7U?ths=true

**Comment by chrissweet** [comment]
I added the documents and tutorials pages. To populate them you have to use the Geonode documents interface for documents set the following after upload:

title (first column of table)              : “njcoast_documentation:Actual Title I want”, the code finds all instances of njcoast_documentation and strips it out from the actual title
Abstract (second column of table): Put the abstract into “Abstract"
Audience (third column of table)   : put the audience data in "Supplemental information”


For the tutorials:

title (first column of table)                  : “njcoast_tutorials: Actual Title I want”, the code finds all instances of njcoast_tutorials and strips it out from the actual title
Scope (second column of table)       : Put the scope into “Abstract”
Link to youTube video and cell color: Put link to video and the color for the LHS table cell into "Supplemental information”. E.g. For the Map Interface we have "https://www.youtube.com/watch?v=WQmpe_-Lz4Q,#FD9438”

Note that both pages are ordered on title, if you need to reorder in a specific way you can prefix the njcoast_x with something to order on like 1,2,3...
