### ISSUE TITLE
GIS Layers are grouped by category

### ISSUE THREAD

**Issue by Omegaice** [NJCoast/cyberspatial#72]
As a user
I want to have layers grouped in categories 
so I can easily navigate them.

AC:

- Layer Groupings: (1) base mapping, (2) property and parcels, (3) emergency operations plan, (4) transportation, (5) planning and zoning, (6) public works, (7) flooding/FEMA and (8) custom hazards.
See accompanying Google Sheet layers  https://goo.gl/RBFUdP identified for Berkeley (B) and Keansburg (KB) for Emergency Management (OEM) and Planning (PLAN).

**Comment by ecaldwe1** [comment]
GIS Layers will have group in the metadata from GeoServer. 
Just add a group field in layer json for now.
