### ISSUE TITLE
Hazard Intensity Visualization within Map

### ISSUE THREAD

**Issue by Omegaice** [NJCoast/cyberspatial#74]
Users should be able to mouse over hazard intensity visualization to see surge height or wind speed at a given location (needs to be specified in GeoJSON model output)

**Comment by ecaldwe1** [comment]
will be given a file with Lat, Lon, Value --- This is the heat map. 
Load the layer with JS or something like that.

Work on getting heatmap plugin installed until James provides the data.
No particular heatmap plugin has been chosen.


This story is getting the heat map layers under a given Storm that is being followed, displayed on the map.
