### ISSUE TITLE
Create Storm Visualization Dropdown Menu

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#75]
As a user
I want to have the ability to browse through real-time storm data, historical data and what-if scenarios.  

AC:

- User can click on storm and a dropdown with layers opens

**Comment by ecaldwe1** [comment]
Pull from json file for now to "check for any updates".
This task covers just showing the orange box when opening the Hazard Layers dropdown.

**Comment by ecaldwe1** [comment]
https://github.com/NJCoast/cyberspatial-ui/pull/6
