### ISSUE TITLE
RSS Feed Storm Data

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#76]
As a user 
I want to see and follow the most recent results of automatic calculations on active storms.

AC:
- Users can decide which are of interest, and click the plus/minus icon on the right to follow/unfollow whichever storms they want at any time.
- Storms the user is “Following” automatically load/reload layers holding the results of the most recent calculations.
- Those storm entries are embedded in an orange box

**Comment by ecaldwe1** [comment]
Can simulate RSS feed with a file that depicts a set of layers

Pull from json file for now to "check for any updates".

name of storm, time, link to layer (heatmap)

Ajax eventually. Keep this frontend as much as possible.

Load page, list of all storms, their layers, and the time. Then set up the JS to check for an update every 6 (maybe 3 for testing) hours.


This story is just listing the active storms in the orange box.
Need to have mechanics of following/unfollowing working. 
Will have to simulate update data.

Will hit endpoint that we will provide (not the national hurricane thing).
Caleb & James need to figure out how we tag active storms or whatever.

**Comment by mkrusche** [comment]
RSS storm dropdown should be open if this is the currently selected storm, after the user followed it again.
